import type { ProcessState } from "./types";

export const demoState: ProcessState = {
  process_id: "demo-process-001",
  fase_atual: "DAV_FLOW",
  sub_fase: "DAV_CHAT",
  dados_carro: {
    "02:Estatuto do sujeito passivo": "Particular",
    "05:Regime de ISV aplicado": null,
    "06:Tipo de identificacao do adquirente/proprietario": "Cartao de Cidadao",
    "06a:Numero de identificacao do adquirente/proprietario": "ID1234567",
    "14:Qualidade da representacao do declarante": "Proprio",
    "17:Tipo de identificacao do declarante": "NIF",
    "17a:Numero de identificacao do declarante": "123456789",
    "18:Nome ou denominacao social do declarante": "Ana Silva Demo",
    "30:Numero de registo no IMT": "2018100025480726",
    "31:Categoria do veiculo": "M1",
    "32:Tipo de veiculo IMT": "Passageiros",
    "33:Tipo de veiculo fiscal": "Ligeiro de passageiros",
    "34:Marca do veiculo": "Example Motors",
    "35:Modelo do veiculo": "A180",
    "36:Variante do veiculo": "X203T2",
    "36a:Versao do veiculo": "EZAA151B",
    "37:Peso bruto do veiculo em kg": "1935",
    "38:Tara do veiculo em kg": "1445",
    "39:Tipo de combustivel": "Diesel",
    "40:Cor do veiculo": "Cinza",
    "41:Tipo de caixa de velocidades": null,
    "42:Numero de quadro (VIN)": "WAUZZZ8V1KA123456",
    "44:Numero de lugares": "5",
    "45:Cilindrada do motor em cm3": "1461",
    "50:Emissoes de CO2 em g/km": "119",
    "55:Estado do veiculo": "Usado",
    "56:Pais de procedencia do veiculo": "Belgica",
    "57:Quilometros do veiculo a data da DAV": "159331",
    "58:Valor comercial do veiculo": "15000.00",
    "60:Data da primeira matricula": "06/12/2019",
    "61:Numero da matricula definitiva": "AA00AA",
    "62:Data de atribuicao da matricula definitiva": "06/12/2019",
    "66:Data de entrada do veiculo em territorio nacional": "20/02/2024",
    "66a:Tipo de entrada do veiculo": "Conduzido pelo proprio",
    "67:Data de apresentacao da DAV": null,
    "69:Tipo de declaracao de importacao": "Definitiva",
    "70:Pais de entrada em livre pratica na UE": null,
    "75:Data da transmissao do veiculo": "10/02/2024",
    "76:Quilometros do veiculo a data da transmissao": "156000",
    "77:Valor de aquisicao do veiculo em euros": "15000.00",
    "78:Taxa de IVA aplicada": null,
    "79:Codigo de isencao de IVA": null,
    "80:Indicacao de operacao nao tributavel": "Operacao intracomunitaria",
    "84:Modo de pagamento": "Transferencia bancaria, Dinheiro",
    "85:Garantia do veiculo": "Venda realizada a profissionais para exportacao sem garantia",
    "86:Fundamento legal": "Artigo 138, paragrafo 1, diretiva 2006/112 da Uniao Europeia",
    "89:Servico emissor do IMT": "IMT - Instituto da Mobilidade e dos Transportes, I.P.",
    "DC01:Nome ou denominacao social do vendedor": "Demo Dealer",
    "DC02:Morada do vendedor": "Rua Exemplo 10, 1000-001 Lisboa, Portugal",
    "DC02a:Pais do vendedor": "Alemanha",
    "DC03:Qualidade do vendedor": "Empresa",
    "DC04:Identificacao fiscal do vendedor": "DE123456789",
    "DC04a:Pais da identificacao fiscal do vendedor": "Alemanha",
    "DC05:Nome ou denominacao social do comprador": "Ana Silva Demo",
    "DC06:Morada do comprador": "Rua do Exemplo 20, 1000-002 Lisboa",
    "DC07:Qualidade do comprador": "Particular",
    "DC08:Identificacao fiscal do comprador": "123456789",
    "DC09:Enquadramento do comprador para efeitos de IVA": null,
    "DC10:Numero da fatura": "10.02.24",
    "DC11:Data da fatura": "10/02/2024",
    "DC12:Regime de tributacao utilizado": "Transmissao intracomunitaria",
    "DC13:Preco do veiculo": "15000.00",
    "DC14:Moeda utilizada": "EUR",
    "DC15:Meio de pagamento da aquisicao": "Transferencia bancaria, Dinheiro",
    "DC16:Existencia de intermediarios na transacao": null,
    "DC21:Meio de transporte utilizado para trazer o veiculo": "Conduzido pelo proprio",
    "DC25:Data de entrada do veiculo em territorio nacional": "20/02/2024",
    "DC26:Forma como teve conhecimento do negocio": null,
    "DC27:Site de internet associado ao negocio": null,
  },
  dados_fiscal: {},
  docs: {
    "1": { category: "CERTIFICADO_MATRICULA", pages: ["1_page_1.jpg", "1_page_2.jpg"], status: "classified" },
    "5": { category: "COMPROVATIVO_INSPECAO_TECNICA", pages: ["5_page_1.jpg"], status: "classified" },
    "6": { category: "FATURA_PROFORMA", pages: ["6_page_1.jpg"], status: "classified" },
    "7": { category: "OUTROS", pages: ["7_page_1.jpg"], status: "classified" },
  },
  flags: {
    ui_out: {
      type: "dav_question",
      message: "Faltam alguns campos de decisao fiscal.",
      fields: [
        { field: "78", label: "Taxa de IVA aplicada", explain: "Percentagem aplicada na compra.", where: "Fatura", examples: ["23"] },
        { field: "67", label: "Data de apresentacao da DAV", explain: "Data em que a DAV vai ser submetida.", where: "Escolha do utilizador", examples: ["21/05/2026"] },
      ],
    },
    dav_field_meta: {
      "17a:Numero de identificacao do declarante": {
        origin: "induced",
        status: "filled",
        reason: "declarante id mirrors comprador tax id",
        source: "DC08",
        value: "123456789",
      },
      "61:Numero da matricula definitiva": {
        origin: "induced",
        status: "filled",
        reason: "matricula found in source documents",
        source: "raw_insights",
        value: "AA00AA",
      },
      "58:Valor comercial do veiculo": {
        origin: "induced",
        status: "filled",
        reason: "commercial value defaults to known acquisition value",
        source: "77",
        value: "15000.00",
      },
      "DC12:Regime de tributacao utilizado": {
        origin: "induced",
        status: "filled",
        reason: "VAT regime inferred from invoice legal basis",
        source: "86",
        value: "Transmissao intracomunitaria",
      },
    },
    agent_progress: [
      {
        id: "demo-upload-1",
        stage: "upload",
        status: "done",
        message: "Uploaded 7 document pages",
        ts: "2026-05-21T20:40:00.000Z",
        detail: { pages: 7 },
      },
      {
        id: "demo-classify-1",
        stage: "classify",
        status: "done",
        message: "Classified registration, inspection and invoice documents",
        ts: "2026-05-21T20:41:00.000Z",
        detail: { documents: 4 },
      },
      {
        id: "demo-extract-1",
        stage: "extract",
        status: "done",
        message: "Extracted structured data from each page",
        ts: "2026-05-21T20:42:00.000Z",
        detail: { pages: 5 },
      },
      {
        id: "demo-harmonize-1",
        stage: "harmonize",
        status: "done",
        message: "Harmonized page evidence into the DAV mirror",
        ts: "2026-05-21T20:43:00.000Z",
        detail: { fields: 72 },
      },
      {
        id: "demo-autofill-1",
        stage: "autofill",
        status: "done",
        message: "Autofilled 16 DAV fields using deterministic equivalences",
        ts: "2026-05-21T20:44:00.000Z",
        detail: { count: 16 },
      },
      {
        id: "demo-review-1",
        stage: "dav_chat",
        status: "warning",
        message: "Prepared 2 DAV review questions",
        ts: "2026-05-21T20:45:00.000Z",
        detail: { review_fields: 2 },
      },
    ],
    extract_job: {
      status: "done",
      started_at: "2026-05-21T20:42:00.000Z",
      finished_at: "2026-05-21T20:43:00.000Z",
      error: null,
      pages_total: 5,
      pages_done: 5,
    },
  },
  prazos: {},
  historico: [
    "Classificou 4 documentos",
    "Fase 1: paginas processadas em paralelo",
    "Auto-preencheu 16 campos DAV por equivalencias/extracao",
  ],
};
